DROP TABLE IF EXISTS user;
CREATE TABLE user
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(16) NOT NULL UNIQUE,
  pass CHAR(32) NOT NULL,
  platform VARCHAR(16) NOT NULL,
  openid VARCHAR(32),
  PRIMARY KEY(id)
)
ENGINE = INNODB DEFAULT CHARACTER SET UTF8;